/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Item, ItemCardVariant, ItemClassName, ItemSlotType, ItemTier, Language, TooltipPlacement, TooltipTrigger } from "./types";
import { ComponentItemInfo } from "./components/dl-item-tooltip/dl-item-tooltip";
import { ComponentItemInfo as ComponentItemInfo1 } from "./components/dl-item-tooltip/dl-item-tooltip";
export { Item, ItemCardVariant, ItemClassName, ItemSlotType, ItemTier, Language, TooltipPlacement, TooltipTrigger } from "./types";
export { ComponentItemInfo } from "./components/dl-item-tooltip/dl-item-tooltip";
export { ComponentItemInfo as ComponentItemInfo1 } from "./components/dl-item-tooltip/dl-item-tooltip";
export namespace Components {
    interface DlItemCard {
        /**
          * Resolved component items data. When provided, skips automatic resolution.
         */
        "componentItemsData"?: ComponentItemInfo[];
        /**
          * Hover effect on the card. `"none"` does nothing, `"scale"` enlarges on hover.
          * @default 'none'
         */
        "hoverEffect": 'none' | 'scale';
        /**
          * Item class name (e.g. `"upgrade_clip_size"`). Alternative to `item-id`.
         */
        "itemClassName"?: ItemClassName;
        /**
          * Pre-loaded item data object. When provided, skips the API fetch.
         */
        "itemData"?: Item;
        /**
          * Item numeric ID. Alternative to `class-name`.
         */
        "itemId"?: number;
        /**
          * Override language for the item name only. Tooltip content uses the global language.
         */
        "itemNameLanguage"?: Language;
        /**
          * Resolved parent items (items this item is a component of).
         */
        "parentItemsData"?: ComponentItemInfo[];
        /**
          * Show the tier badge on hover. When not set, falls back to the global provider value.
         */
        "showTierBadge"?: boolean;
        /**
          * Override the tooltip trigger for this card. When not set, falls back to the global provider value.
         */
        "tooltipTrigger"?: TooltipTrigger;
        /**
          * Visual variant. `"card"` renders the full shop card; `"image"` renders only the square item image; inline variants render text/image triggers.
          * @default 'card'
         */
        "variant": ItemCardVariant;
    }
    interface DlItemGrid {
        /**
          * When `true`, only shows items available in the shop.
          * @default true
         */
        "shopableOnly": boolean;
        /**
          * Filter items by slot type: `"weapon"`, `"vitality"`, or `"spirit"`.
         */
        "slotType"?: ItemSlotType;
        /**
          * Filter items by tier (1–4).
         */
        "tier"?: ItemTier;
    }
    interface DlItemTooltip {
        /**
          * Resolved component items to display at the bottom of the tooltip.
         */
        "componentItemsData"?: ComponentItemInfo1[];
        /**
          * Item class name (e.g. `"upgrade_capacitor"`). Alternative to `item-id`.
         */
        "itemClassName"?: ItemClassName;
        /**
          * Pre-loaded item data object. When provided, skips the API fetch.
         */
        "itemData"?: Item;
        /**
          * Item numeric ID. Alternative to `class-name`.
         */
        "itemId"?: number;
        /**
          * Fetch and display the item name in a different language than the global config.
         */
        "itemNameLanguage"?: Language;
        /**
          * Override the item name displayed in the tooltip header.
         */
        "nameOverride"?: string;
        /**
          * Resolved parent items (items this item is a component of).
         */
        "parentItemsData"?: ComponentItemInfo1[];
    }
    interface DlProvider {
        /**
          * Language for item data (e.g. `"english"`, `"brazilian"`, `"japanese"`).
          * @default Language.EN
         */
        "language": Language;
        /**
          * Show numeric scaling multipliers in item tooltips. When false, only scaling icons and strength arrows are shown.
          * @default false
         */
        "showScalingValues": boolean;
        /**
          * Show tier badge on item cards globally. Individual cards can override this.
          * @default true
         */
        "showTierBadge": boolean;
        /**
          * Delay in milliseconds before showing the tooltip on hover.
          * @default 100
         */
        "tooltipDelay": number;
        /**
          * When `true`, the tooltip follows the cursor instead of anchoring to the card. Only applies when `tooltip-trigger` is `"hover"`.
          * @default false
         */
        "tooltipFollowCursor": boolean;
        /**
          * Preferred tooltip position. `"auto"` picks the side with the most space.
          * @default 'auto'
         */
        "tooltipPlacement": TooltipPlacement;
        /**
          * How the item tooltip is triggered: `"hover"` on mouse over, `"click"` on click, or `"none"` to disable.
          * @default 'hover'
         */
        "tooltipTrigger": TooltipTrigger;
    }
    interface DlShopPanel {
        /**
          * The tab to display initially. One of `"weapon"`, `"vitality"`, or `"spirit"`.
          * @default 'weapon'
         */
        "activeTab": ItemSlotType;
        /**
          * When `true`, disables the highlight effect that dims unrelated items on hover.
          * @default false
         */
        "disableHighlight": boolean;
        /**
          * Hover effect applied to each item card. One of `"none"` or `"scale"`.
          * @default 'scale'
         */
        "hoverEffect": 'none' | 'scale';
        /**
          * Override language for item names only. Tooltip content uses the global language.
         */
        "itemNameLanguage"?: Language;
        /**
          * Override the Spirit tab background image URL.
         */
        "shopBackgroundSpirit"?: string;
        /**
          * Override the Vitality tab background image URL.
         */
        "shopBackgroundVitality"?: string;
        /**
          * Override the Weapon tab background image URL.
         */
        "shopBackgroundWeapon"?: string;
    }
}
export interface DlItemCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDlItemCardElement;
}
declare global {
    interface HTMLDlItemCardElementEventMap {
        "tooltipOpen": string;
        "tooltipClose": string;
    }
    interface HTMLDlItemCardElement extends Components.DlItemCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDlItemCardElementEventMap>(type: K, listener: (this: HTMLDlItemCardElement, ev: DlItemCardCustomEvent<HTMLDlItemCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDlItemCardElementEventMap>(type: K, listener: (this: HTMLDlItemCardElement, ev: DlItemCardCustomEvent<HTMLDlItemCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDlItemCardElement: {
        prototype: HTMLDlItemCardElement;
        new (): HTMLDlItemCardElement;
    };
    interface HTMLDlItemGridElement extends Components.DlItemGrid, HTMLStencilElement {
    }
    var HTMLDlItemGridElement: {
        prototype: HTMLDlItemGridElement;
        new (): HTMLDlItemGridElement;
    };
    interface HTMLDlItemTooltipElement extends Components.DlItemTooltip, HTMLStencilElement {
    }
    var HTMLDlItemTooltipElement: {
        prototype: HTMLDlItemTooltipElement;
        new (): HTMLDlItemTooltipElement;
    };
    interface HTMLDlProviderElement extends Components.DlProvider, HTMLStencilElement {
    }
    var HTMLDlProviderElement: {
        prototype: HTMLDlProviderElement;
        new (): HTMLDlProviderElement;
    };
    interface HTMLDlShopPanelElement extends Components.DlShopPanel, HTMLStencilElement {
    }
    var HTMLDlShopPanelElement: {
        prototype: HTMLDlShopPanelElement;
        new (): HTMLDlShopPanelElement;
    };
    interface HTMLElementTagNameMap {
        "dl-item-card": HTMLDlItemCardElement;
        "dl-item-grid": HTMLDlItemGridElement;
        "dl-item-tooltip": HTMLDlItemTooltipElement;
        "dl-provider": HTMLDlProviderElement;
        "dl-shop-panel": HTMLDlShopPanelElement;
    }
}
declare namespace LocalJSX {
    interface DlItemCard {
        /**
          * Resolved component items data. When provided, skips automatic resolution.
         */
        "componentItemsData"?: ComponentItemInfo[];
        /**
          * Hover effect on the card. `"none"` does nothing, `"scale"` enlarges on hover.
          * @default 'none'
         */
        "hoverEffect"?: 'none' | 'scale';
        /**
          * Item class name (e.g. `"upgrade_clip_size"`). Alternative to `item-id`.
         */
        "itemClassName"?: ItemClassName;
        /**
          * Pre-loaded item data object. When provided, skips the API fetch.
         */
        "itemData"?: Item;
        /**
          * Item numeric ID. Alternative to `class-name`.
         */
        "itemId"?: number;
        /**
          * Override language for the item name only. Tooltip content uses the global language.
         */
        "itemNameLanguage"?: Language;
        /**
          * Emitted when the tooltip closes. Detail contains the item's `class_name`.
         */
        "onTooltipClose"?: (event: DlItemCardCustomEvent<string>) => void;
        /**
          * Emitted when the tooltip opens. Detail contains the item's `class_name`.
         */
        "onTooltipOpen"?: (event: DlItemCardCustomEvent<string>) => void;
        /**
          * Resolved parent items (items this item is a component of).
         */
        "parentItemsData"?: ComponentItemInfo[];
        /**
          * Show the tier badge on hover. When not set, falls back to the global provider value.
         */
        "showTierBadge"?: boolean;
        /**
          * Override the tooltip trigger for this card. When not set, falls back to the global provider value.
         */
        "tooltipTrigger"?: TooltipTrigger;
        /**
          * Visual variant. `"card"` renders the full shop card; `"image"` renders only the square item image; inline variants render text/image triggers.
          * @default 'card'
         */
        "variant"?: ItemCardVariant;
    }
    interface DlItemGrid {
        /**
          * When `true`, only shows items available in the shop.
          * @default true
         */
        "shopableOnly"?: boolean;
        /**
          * Filter items by slot type: `"weapon"`, `"vitality"`, or `"spirit"`.
         */
        "slotType"?: ItemSlotType;
        /**
          * Filter items by tier (1–4).
         */
        "tier"?: ItemTier;
    }
    interface DlItemTooltip {
        /**
          * Resolved component items to display at the bottom of the tooltip.
         */
        "componentItemsData"?: ComponentItemInfo1[];
        /**
          * Item class name (e.g. `"upgrade_capacitor"`). Alternative to `item-id`.
         */
        "itemClassName"?: ItemClassName;
        /**
          * Pre-loaded item data object. When provided, skips the API fetch.
         */
        "itemData"?: Item;
        /**
          * Item numeric ID. Alternative to `class-name`.
         */
        "itemId"?: number;
        /**
          * Fetch and display the item name in a different language than the global config.
         */
        "itemNameLanguage"?: Language;
        /**
          * Override the item name displayed in the tooltip header.
         */
        "nameOverride"?: string;
        /**
          * Resolved parent items (items this item is a component of).
         */
        "parentItemsData"?: ComponentItemInfo1[];
    }
    interface DlProvider {
        /**
          * Language for item data (e.g. `"english"`, `"brazilian"`, `"japanese"`).
          * @default Language.EN
         */
        "language"?: Language;
        /**
          * Show numeric scaling multipliers in item tooltips. When false, only scaling icons and strength arrows are shown.
          * @default false
         */
        "showScalingValues"?: boolean;
        /**
          * Show tier badge on item cards globally. Individual cards can override this.
          * @default true
         */
        "showTierBadge"?: boolean;
        /**
          * Delay in milliseconds before showing the tooltip on hover.
          * @default 100
         */
        "tooltipDelay"?: number;
        /**
          * When `true`, the tooltip follows the cursor instead of anchoring to the card. Only applies when `tooltip-trigger` is `"hover"`.
          * @default false
         */
        "tooltipFollowCursor"?: boolean;
        /**
          * Preferred tooltip position. `"auto"` picks the side with the most space.
          * @default 'auto'
         */
        "tooltipPlacement"?: TooltipPlacement;
        /**
          * How the item tooltip is triggered: `"hover"` on mouse over, `"click"` on click, or `"none"` to disable.
          * @default 'hover'
         */
        "tooltipTrigger"?: TooltipTrigger;
    }
    interface DlShopPanel {
        /**
          * The tab to display initially. One of `"weapon"`, `"vitality"`, or `"spirit"`.
          * @default 'weapon'
         */
        "activeTab"?: ItemSlotType;
        /**
          * When `true`, disables the highlight effect that dims unrelated items on hover.
          * @default false
         */
        "disableHighlight"?: boolean;
        /**
          * Hover effect applied to each item card. One of `"none"` or `"scale"`.
          * @default 'scale'
         */
        "hoverEffect"?: 'none' | 'scale';
        /**
          * Override language for item names only. Tooltip content uses the global language.
         */
        "itemNameLanguage"?: Language;
        /**
          * Override the Spirit tab background image URL.
         */
        "shopBackgroundSpirit"?: string;
        /**
          * Override the Vitality tab background image URL.
         */
        "shopBackgroundVitality"?: string;
        /**
          * Override the Weapon tab background image URL.
         */
        "shopBackgroundWeapon"?: string;
    }

    interface DlItemCardAttributes {
        "itemId": number;
        "itemClassName": ItemClassName;
        "hoverEffect": 'none' | 'scale';
        "variant": ItemCardVariant;
        "showTierBadge": boolean;
        "itemNameLanguage": Language;
        "tooltipTrigger": TooltipTrigger;
    }
    interface DlItemGridAttributes {
        "slotType": ItemSlotType;
        "tier": ItemTier;
        "shopableOnly": boolean;
    }
    interface DlItemTooltipAttributes {
        "itemId": number;
        "itemClassName": ItemClassName;
        "nameOverride": string;
        "itemNameLanguage": Language;
    }
    interface DlProviderAttributes {
        "language": Language;
        "tooltipTrigger": TooltipTrigger;
        "tooltipPlacement": TooltipPlacement;
        "tooltipFollowCursor": boolean;
        "tooltipDelay": number;
        "showTierBadge": boolean;
        "showScalingValues": boolean;
    }
    interface DlShopPanelAttributes {
        "activeTab": ItemSlotType;
        "hoverEffect": 'none' | 'scale';
        "disableHighlight": boolean;
        "itemNameLanguage": Language;
        "shopBackgroundWeapon": string;
        "shopBackgroundVitality": string;
        "shopBackgroundSpirit": string;
    }

    interface IntrinsicElements {
        "dl-item-card": Omit<DlItemCard, keyof DlItemCardAttributes> & { [K in keyof DlItemCard & keyof DlItemCardAttributes]?: DlItemCard[K] } & { [K in keyof DlItemCard & keyof DlItemCardAttributes as `attr:${K}`]?: DlItemCardAttributes[K] } & { [K in keyof DlItemCard & keyof DlItemCardAttributes as `prop:${K}`]?: DlItemCard[K] };
        "dl-item-grid": Omit<DlItemGrid, keyof DlItemGridAttributes> & { [K in keyof DlItemGrid & keyof DlItemGridAttributes]?: DlItemGrid[K] } & { [K in keyof DlItemGrid & keyof DlItemGridAttributes as `attr:${K}`]?: DlItemGridAttributes[K] } & { [K in keyof DlItemGrid & keyof DlItemGridAttributes as `prop:${K}`]?: DlItemGrid[K] };
        "dl-item-tooltip": Omit<DlItemTooltip, keyof DlItemTooltipAttributes> & { [K in keyof DlItemTooltip & keyof DlItemTooltipAttributes]?: DlItemTooltip[K] } & { [K in keyof DlItemTooltip & keyof DlItemTooltipAttributes as `attr:${K}`]?: DlItemTooltipAttributes[K] } & { [K in keyof DlItemTooltip & keyof DlItemTooltipAttributes as `prop:${K}`]?: DlItemTooltip[K] };
        "dl-provider": Omit<DlProvider, keyof DlProviderAttributes> & { [K in keyof DlProvider & keyof DlProviderAttributes]?: DlProvider[K] } & { [K in keyof DlProvider & keyof DlProviderAttributes as `attr:${K}`]?: DlProviderAttributes[K] } & { [K in keyof DlProvider & keyof DlProviderAttributes as `prop:${K}`]?: DlProvider[K] };
        "dl-shop-panel": Omit<DlShopPanel, keyof DlShopPanelAttributes> & { [K in keyof DlShopPanel & keyof DlShopPanelAttributes]?: DlShopPanel[K] } & { [K in keyof DlShopPanel & keyof DlShopPanelAttributes as `attr:${K}`]?: DlShopPanelAttributes[K] } & { [K in keyof DlShopPanel & keyof DlShopPanelAttributes as `prop:${K}`]?: DlShopPanel[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dl-item-card": LocalJSX.IntrinsicElements["dl-item-card"] & JSXBase.HTMLAttributes<HTMLDlItemCardElement>;
            "dl-item-grid": LocalJSX.IntrinsicElements["dl-item-grid"] & JSXBase.HTMLAttributes<HTMLDlItemGridElement>;
            "dl-item-tooltip": LocalJSX.IntrinsicElements["dl-item-tooltip"] & JSXBase.HTMLAttributes<HTMLDlItemTooltipElement>;
            "dl-provider": LocalJSX.IntrinsicElements["dl-provider"] & JSXBase.HTMLAttributes<HTMLDlProviderElement>;
            "dl-shop-panel": LocalJSX.IntrinsicElements["dl-shop-panel"] & JSXBase.HTMLAttributes<HTMLDlShopPanelElement>;
        }
    }
}
